### ISSUE TITLE
Revisions Tracking Issue

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy-articles#65]
Based on a full read-through of the manuscript on January 11/ 2019, my detailed revision notes/ check-list is below & of course open to adjustment, etc. Some of the objectives of the revisions at this stage include unifying the paper to a "coherent voice" / style, looking at concision / focus due to its length, and considering the [submission requirements](https://www.nature.com/srep/publish/guidelines) of the journal *Scientific Reports* as well.

- [ ] format our manuscript for submission based on the Journal format requirements:
- > "Scientific Reports publishes original research in one format, Article. In most cases we do not impose strict limits on word counts and page numbers, but we encourage authors to write concisely and suggest authors adhere to the guidelines below."
  - > Articles should be no more than 11 typeset pages in length
  - > the main text (not including Abstract, Methods, References and figure legends) should be no more than 4,500 words.
  - > The manuscript text file should include the following parts, in order: 
    - > a title page with author affiliations and contact information (the corresponding author should be identified with an asterisk). 
    - > The main text of an Article can be organised in different ways and according to the authors' preferences, it may be appropriate to combine sections.
    - > Figure Legends (these are limited to 350 words per figure) 
    - > Tables (maximum size of one page)
   - [x] Footnotes are not used.
  - > authors may choose to incorporate the manuscript text and figures into a single file up to 3 MB in size in either a Microsoft Word, LaTeX, or PDF format - the figures may be inserted within the text at the appropriate positions, or grouped at the end.

**Notes / check-list as I read through the paper**:
- **Introduction**  [my general thought on the intro section is that it is rather anecdotal & would benefit from at least bolstering with some more citations -- i.e., cite conference proceedings instead of just mentioning social events / community & so on; also may consider effectively fusing with Background, which is also anecdotal]
  - [x] add citation / link for the published SciPy-importing LIGO scripts mentioned
  - [x] in the first paragraph we should immediately add some kind of citation for NumPy & explain briefly what it is for the audience of the journal
  - [x] citation for "...backed by millions in funding, and thousands of highly qualified engineers..."
  - [x] citation for "...entire ecosystem of related packages..." &
  - [x] "...a variety of social activities centered around them" (cite conferences?? it is done a bit later, but either do it first here or remove)
- **Background** [anecdotal, but mostly with appropriate citations -- some subsections are noted to need some development and / or cleanup + one or two are abrupt changes in direction from the prose that precedes them]
  - [x] first paragraph -- one thought here: this is a scientific journal, so we could mention that Python is a dynamically typed language & also cite the most popular CPython implementation with the highly-cited Python - C API reference manual produced by Guido
  - [ ] "A number of these packages were written by graduate students and postdoctoral researchers to solve the very practical research problems that they faced on a daily basis."
    - [ ] try to bolster this anecdote with example project / package citation?
  - [x] "Wingware’s C++ Visualization Toolkit" --> should be Kitware now, I think, and cite?
  - [x] cite Project Jupyter at first mention?
  - "NumPy 1.0 was released in October 2006"
    - [x] this text renders in red but has no period or citation -- misplaced?
      - perhaps this needs a one or two-sentence expansion -- NumPy became the new standard for the array & is now ubiquitous
  - [x] we only now mention that Python is "interpreted," from Paul Dubois quote -- these language specification details (interpreted, dynamically typed) for Python should be mentioned early on, I think
  - "In addition to these longer introductory articles," 
    - [x] repeat on "In addition" from last sentence
  - [x] the tense of the prose in the first paragraph of the "SciPy Matures" subsection feels a little off
  - "special issues are organized and published in a leading scientific magazine,"
    - [x] cite it?
  - [ ] prose tense issues continue a bit in subsequent parts
  - "While the US SciPy conference kept growing (by ... it had multiple tracks"
    - [x] this needs to be filled in or removed
  - "When Paul edited the CiSE..."
    - [x] let's use surnames consistently in the paper I think -- there are a lot of authors / contributors, even if we might assume from the context...
    - [x] what is CiSE?
    - [x] this sentence needs a cleanup in structure too
  - "...NumFOCUS organizes a global network of community driven educational program called PyData"
    - [x] maybe conferences / meetups instead of or in addition to program?
    - [x] certainly program should be plural at least?
  - [x] the "Project Scope" subsection is a bit of a sudden switch away from the anecdotal material that preceeds it for much of the background
  - "...SciPy provides what one expect to find..."
    - [x] cite the other projects mentioned in this sentence, at least if they haven't already been cited before in the paper
    - [x] plural expects
    - [x] the sentence is then abruptly followed with an unlabeled list, and this needs to be cleaned up
  - Current status (maturity, users) subsection
    - [x] this subsection looks messy / undeveloped with question marks and ellipses & then just mentioning the timeline figure which isn't even cited in LaTeX
- **Architecture and implementation choices**
  - **Submodule organization**
      - [ ] for constants -- should we mention our policy on frequency of updates? I saw an issue about this recently with some metric things being refined I think; maybe a minor point though
      - [ ] would it be neat / useful to add the years the subpackages were first present in SciPy?
      - [ ] Is this subsection more appriopriately presented as a Table proper to condense the content? The extended list of definitions in journal paragraph format may be awkward -- conversely, the Table might get pretty tightly packed
       - [ ] citations for wrapped packages like FITPACK & ODRPACK mentioned in this subsection?
         - we might as well, they're already cited in the language choices section below
  - **Common Infrastructure**
    - [x] This subsection is blank -- do we want to keep it?
  - **Language choices**
    - [x] should maybe cite `linguist` library repo
  - **API and ABI evolution**
- **Key technical improvements** (last 3 years)
  - **Data Structures**
    - **cKDTree** ~[*this section needs major revision / clarification / TODO items completed / some material moved to SI?*]~
      - [x] can we really get away with inline discussions that include the assumption that the reader will understand something like "np.arange(max(k))"? because we have that  at the moment here
      - [x] the second and third paragraphs are extremely technical -- we may have to simplify this a little bit; it is hard for me to read & wrote some of it too--the other problem with presenting this clearly is that the original authors of the code have limited time to write clear prose  about what they did and what algorithms they used
       - [x] sentence starting "The cKDTree module implements a dual tree counting algorithm..." is a bit sudden / list-like
       - [x] There's a TODO-style sentence in this section with "Add a Figure to show the scaling, before and after. perhaps give an example or some formula. (cite / mention faster implementions of paircounting algorithms / treecorr, corrfunc)"
          - again, as noted above, clear & concise presentation of this information would benefit from consultation of original authors and / or close & careful study of the source code
    - **sparse matrices**
      - [x] provide citations for those performance improvements (Pauli's asv website or??)
      - the section is otherwise short & sweet, which is good
  - **Unified bindings to compiled code**
    - **LowLevelCallable**
      - probably okay, albeit fairly obscure discussion outside Scientific Python community
  - **Cython bindings for BLAS, LAPACK, and special**
    - [x] this is a subsection of "technical improvements" -- if this was one of the things added in last 3 years we should clarify that somewhere in the discussion -- i.e., switch language from "Scipy includes... " to "Scipy now includes..."
     - otherwise, the section is quite readable, I think
  - **Numerical optimization**
    - [x] I suspect we should remove the background on what scipy.optimize does with the list of 7 problems -- we should find a way to make this relatively clear & abstract that information to earlier in the paper when the 16 SciPy submodules are described
    - [x] Just focus on improvements -- can even remove sentence "Documentation of SciPy’s functionality in each these areas can be found in (cite SciPy documentation)..."
      - **Linear optimization**
        - well-written: indicates new algorithm implemented, what it does, and what can be done to improve in future
      - **Nonlinear optimization**
        - **Local**
          - [ ] Table 1 is nice; the sentence citing it should mention that it includes some of the more recent additions since we're still in the umbrella of key / recent technical improvements
          - [x] that said, Table 1 also includes additions from as far back as SciPy 0.6 -- which is a longer time span than "last 3 years" for the improvements section as a whole...
             - [x] ~what about i.e., a dashed vertical line / highlight of some sort dividing "last 3 years" and "before that" in the Table?~
           - [x] The Table caption is very detailed, but I'm a little concerned about its size -- could we cut it down a bit and move some of the heavy details to i.e., supporting information? [**entire Table now in SI**]
           - [ ] I think we do have to move some of the context in the paragraphs here away so that only "last 3 years" / new stuff is emphasized and the older things are either abstracted to the supporting info or moved to the table summarizing what the 16 SciPy submodules do
               - [ ] for example, Nelder-Mead, Powell and COBYLA are discussed but from version 0.6 or earlier, so maybe best relocated
               - there's a paragraph starting "One recently-added trust-region method is trust-exact..." -- this is the kind of content we want here
        - **Global**
          - [ ] it is not clear to me which parts of the discussion here fall into the relevant "last 3 years" improvements category, and which are better placed in SI or a previous discussion of what SciPy can do more broadly
  - **Statistical distributions**
    - [ ] this can be condensed (maybe?) to only include the recent improvements -- there's too much material about what scipy.stats does more broadly, I think; that material should perhaps either be moved to SI / the general Table, or somewhere else?
  - **Polynomial interpolators**
    - [ ] "UnivariateSpline and splrep/splev combo" -> combination
    - [ ] there's also a fair bit of background for this subsection before we get to the new stuff, but perhaps it is sufficiently convoluted that at least some background is justified
    - [ ] I suspect we could make some effort to clarify old vs. new here & to migrate some of the material that is more "user guide / reference" like elsewhere
  - **Test and benchmark suite**
    - [ ] I suppose it isn't fully clear which testing / performance things are from the last 3 years vs. much older
    - **Benchmark suite**
      - [x] cite `asv` library repo maybe?
      - [x] the "see above" comment re: unit tests may now be below?
      - [x] shouldn't the "python run.py" command just be "asv run"? maybe it was supposed to be runtests.py or the custom SciPy handler, but using asv directly is probably preferred anyway
      - [ ] Fig 4.:  I've previously had concerns that it is a little unprofessional to use a screen capture for a Figure in a scientific journal, but I think someone commented that it is ok to show the "true output"
      - [x] "the documentation" should probably be "the asv documentation" in last paragraph
    - **Test suite**
      - [ ] Figure 5: bizarre dips and lack of x-axis label / our inability to modify the figure easily for reviewers seem problematic
        - [ ] we could try to regenerate this programmatically using coverage code over the commit history of the project, but that may be a bit of an undertaking to get right
- **Project organization and community**
  - **Governance**
    - seems ok
  - **Roadmap**
    - [x] this still reads like an awkward list -- should it be a Table or fully fleshed out prose?
  - **Community beyond the SciPy library**
    - [x] this is ok; another example might not hurt
  - **Maintainers and contributors**
    - [x] citation / link for SciPy Developer Guide maybe
- **Discussion**
  - [ ] Still contains TODO-style sentences like "The Discussion should be succinct and must not contain subheadings."
  - **Impact now**
    - Good enough I think
    - ~[x] the > 13 M downloads Figure may be good to mention in the Abstract as well for "wow" factor I suppose~
  - **Future development**
    - [x] Condense the PyData sparse content a little maybe & update if appropriate given any recent roadmap / plan adjustments?
    - [x] there is **nothing else** in this section -- perhaps just refer back to the roadmap then, or combine roadmap and future directions somehow??
- **Acknowledgments**
  - [ ] TODO
- **Author contributions statement**
  - [ ] TODO
- **Additional information**
  - [ ] TODO
  - [ ] Competing Interests Statement -- contributors with company affiliations that might be perceived as a conflict of interest?
- **Supporting Information**
  - [x] TODO / maybe?

**Comment by jarrodmillman** [comment]
I am not sure how to justify "...backed by millions in funding, and thousands of highly qualified engineers...".  I suppose we would need to get a list of the major projects and look at their revenue and staff.  This would include at least Matlab and IDL, but others as well.  It seemed like a pretty conservative estimate at the time, but I don't think we tried to actual calculate the numbers.

According to wikipedia:
"By 1997, MathWorks was profitable, claiming revenue of around $50 million, and had around 380 employees."

And according to this:
 http://web.cba.neu.edu/~mmeyer/courses/platforms/mathworks.pdf
MathWorks' 1998 yearly revenue reached $100 million.

So maybe we could say
"...backed by tens of millions in funding..."
and sight the article cited by wikipedia:

Blanton, Kimberly (20 April 1997). "At Mathworks, support + fun = success CEO Jack Little believes in power of his workers -- and their ideas". The Boston Globe. p. J5. 

It is still an underestimate, but we at least have something to cite.

**Comment by tylerjereddy** [comment]
Yeah, that's exactly the kind of thing I had in mind. Probably doesn't have to be thorough, but a citation of some sort so it isn't a "vapor" claim seems useful. Maybe I'm just too picky.

**Comment by mdhaber** [comment]
@tylerjereddy  Not too picky. This was a comment of mine, too.

**Comment by tylerjereddy** [comment]
I've crossed out the proposed Abstract improvement re: citing Download figures after a bit more though -- if others would prefer to include that feel free to open a PR. On balance, people were mostly happy with the abstract on the early draft & keeping it short is good.

**Comment by tylerjereddy** [comment]
At this point, I'll likely let others open PRs to address issues above (or otherwise) they agree with--that way I'm less likely to put time into a change for which there is not a consensus.

**Comment by tylerjereddy** [comment]
Around 45 % of the way through the checklist now; I'll see what else I can do. I'll aim for leaving PRs open ~1 week before I go for self-merge, as usual for the articles repo.

**Comment by tylerjereddy** [comment]
I've marked the community beyond scipy library part as completed as we probably don't want the suggested expansion with another example given current size of paper.

**Comment by tylerjereddy** [comment]
About 55 % now, with probably some more easy ones left, and probably some that can simply be eliminated by consensus.

The revised code line coverage plot will be a pain to do. I failed an initial / quick attempt last week -- it is tricky to set up locally and reliably across project history, but probably doable with some care.

**Comment by chrisb83** [comment]
@tylerjereddy I had a look at the stats section and I agree that the section could be condensed. I will try to give feedback this weekend

**Comment by rgommers** [comment]
> The revised code line coverage plot will be a pain to do. I failed an initial / quick attempt last week -- it is tricky to set up locally and reliably across project history, but probably doable with some care.

Maybe consider leaving it out to avoid the pain, unless it becomes more informative? I think it's more or less a straight horizontal line for the past few years anyway.

**Comment by rgommers** [comment]
nice comprehensive checklist @tylerjereddy

**Comment by mdhaber** [comment]
@tylerjereddy Could you take a look at the most recent draft:
https://427-66140682-gh.circle-artifacts.com/0/papers/artifacts/paper.pdf
and see which items of your checklist remain? 
Maybe we should condense the list of those that remain or start issues for any big ones?

**Comment by tylerjereddy** [comment]
I'll do maybe one more full read through, but only if there are no other substantial changes planned at this stage. It took the better part of a full day for me to read the manuscript & generate this checklist last time.

The checklist was produced on the vision that the paper was to be unified in one coherent voice, but there have since been several changes that I've not agreed with, so I really can't speak to the validity of this checklist anymore.

Feel free to close and move forward--let's get this submitted soon!

**Comment by rgommers** [comment]
> I'll do maybe one more full read through, but only if there are no other substantial changes planned at this stage.

As far as I can tell, nothing major anymore. In several places some small tweaks, I think I commented on all of the proposals of @mdhaber (and again my apologies for being slow). The main paper looks good.

The SI could use a bit of pruning. Imho the best section is the overview of `optimize`, with table S1. Perhaps move that to the front.

**Comment by rgommers** [comment]
Acknowledgements: perhaps throw that out, not feasible to pick specific people or organizations for inclusion.

**Comment by tylerjereddy** [comment]
These revisions were pre-submission & we're now finishing up post-review adjustments, so long past due to close this issue.
